#!/usr/bin/env bash

# Find and kill the 7-highlander process
pid=$(pgrep -f "7-highlander")
if [ -n "$pid" ]; then
    echo "Killing the 7-highlander process with PID $pid"
    kill -15 "$pid"
else
    echo "No 7-highlander process found"
fi
