#!/usr/bin/env bash
# This script changes the resolution of localhost and facebook.comcp /etc/hosts ~/hosts.new

echo "127.0.0.2     localhost" >~/hosts.new
echo "8.8.8.8       facebook.com" >>~/hosts.new
cat ~/hosts.new >/etc/hosts
