#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it's executed on.

# Get all IP addresses from the 'ip addr' command, filter for IPv4 addresses,
# and then remove all non-IP text.
ip addr | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1
